const config = {
    NAME: 'SONIVERSE',
    RPC_URL: 'https://jakartanet.smartpy.io',
    NETWORK: 'jakartanet',
    CONTRACT_ADDRESS : "KT1ENHhnX1N3qQJvfsq9ZxjdjjbZeGWSqmGm", 
    TOKEN_ADDRESS: "KT1NJMwb5DeVUCPzzL4VqscMh1RfZquBHSPy",
    IPFS_W3S_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGJBNzBhMTgxMmEwODA0QzFGQjRGMmU4MzUxMEExNDU5YTVERjczYTMiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NDgwNjQ5NjU4NTAsIm5hbWUiOiJBVVhBIn0.HeikzhQrGiOZPuIciHQYko4IlNhSeV35EyHwrWPYW9k",
    IPFS_NFTS_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGMyNDgyYTQ4OEZlMzJCRWI4Njg2NzQzNjNlMTE3NzQ2MWJFNTk5M0IiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY0ODA0MDEwNDcyOSwibmFtZSI6IkFVWEEifQ.Qg37_Klf47XTqKEfeHserro_i_k-wKbjImtQVgHrLN8"
}

export default config;