const config = {
    NAME: 'SONIVERSE',
    RPC_URL: 'https://kathmandunet.smartpy.io',
    NETWORK: 'kathmandunet',
    CONTRACT_ADDRESS : "KT1QuAxw3bm1ct2J8oiq6RAy1h75CHkNvrm7", 
    TOKEN_ADDRESS: "KT1H9bSBD9tJYYKRY8aXAbT4MPQpwQ7VEScA",
    IPFS_W3S_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGJBNzBhMTgxMmEwODA0QzFGQjRGMmU4MzUxMEExNDU5YTVERjczYTMiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NDgwNjQ5NjU4NTAsIm5hbWUiOiJBVVhBIn0.HeikzhQrGiOZPuIciHQYko4IlNhSeV35EyHwrWPYW9k",
    IPFS_NFTS_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGMyNDgyYTQ4OEZlMzJCRWI4Njg2NzQzNjNlMTE3NzQ2MWJFNTk5M0IiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY0ODA0MDEwNDcyOSwibmFtZSI6IkFVWEEifQ.Qg37_Klf47XTqKEfeHserro_i_k-wKbjImtQVgHrLN8"
}

export default config;